site_name: ""
site_url: https://platinfra.github.io/
repo_name: platinfra
repo_url: https://github.com/platinfra/platinfra
edit_uri: edit/main/docs/

strict: true
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Introduction: index.md
  - User Guide:
      - user_guide/index.md
      - Stack config:
          - user_guide/stack_config/index.md
          - Provider: user_guide/stack_config/provider.md
          - Deployment: user_guide/stack_config/deployment.md
          - Stack: user_guide/stack_config/stack.md
        # - Cloud Config:
        #     -
        # - Applications Config:
  # - Tutorials:
  # - API Reference:
  - Release Notes: RELEASE_NOTES.md
  - Contributing: CONTRIBUTING.md
  - Reporting Security Vulnerabilities: SECURITY.md
  - Roadmap: roadmap.md
  - Acknowledgements: acknowledgements.md
  - About Me: about_me.md

theme:
  name: "material"
  custom_dir: docs/overrides
  font:
    text: Raleway
    code: mononoki
  logo: _images/platinfra-white.png
  favicon: _images/platinfra-minimal-white.png
  features:
    # - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - content.action.edit
    # - navigation.tabs
    # - navigation.tabs.sticky
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep orange
      accent: yellow
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep orange
      accent: yellow
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: deep orange
      accent: yellow
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: material/lightbulb-alert

markdown_extensions:
  - abbr
  - tables
  - def_list
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  homepage: https://platinfra.github.io/
  generator: false
  version:
    provider: mike
    default: latest
  analytics:
    provider: custom
    api_key: 167aefed6bd10a9200b052a52504ff5
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aliabbasjaffri
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/platinfra
    - icon: fontawesome/brands/discord
      link: https://discord.gg/BwuMen4XEE
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aliabbasjaffri/
    - icon: fontawesome/brands/medium
      link: https://medium.com/@aliabbasjaffri_/
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics: analytics by amplitude
    actions:
      - accept

plugins:
  - privacy
  - search
  - section-index
  - git-revision-date-localized:
      enable_creation_date: false
      type: iso_date

copyright: >
  Copyright &copy; 2023 - 2024 platinfra –
  <a href="#__consent">Change cookie settings</a>
