site_name: platinfra
site_url: https://platinfra.github.io/
repo_url: https://github.com/platinfra/platinfra

# To validate all internal links exist. Does not work in ipynb files
strict: true
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  name: "material"
