site_name: platinfra
site_url: https://platinfra.github.io/
repo_url: https://github.com/platinfra/platinfra

# To validate all internal links exist. Does not work in ipynb files
strict: true
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Home: index.md
  # - User Guide:
  # - Tutorials:
  # - API Reference:
  - Contributing: CONTRIBUTING.md

theme:
  name: "material"
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
