name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report!"

  - type: input
    id: system-information
    attributes:
      label: System Information
      description: "Please provide details about your Python and Terraform environment. Include Python version, Terraform version, and any relevant dependencies or modules."
      placeholder: "e.g., Python 3.10.0, Terraform v1.6.0"
    validations:
      required: true

  - type: textarea
    id: issue-details
    attributes:
      label: Issue Details
      description: "Please provide a clear and concise description of the problem."
      placeholder: "Describe the bug..."
    validations:
      required: true

  - type: textarea
    id: reproducibility-steps
    attributes:
      label: Steps to Reproduce
      description: "Please provide a step-by-step process to reproduce the issue."
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Code of Conduct\nBy submitting this issue, I agree to abide by the [Code of Conduct](https://github.com/platinfra/platinfra/blob/main/CODE_OF_CONDUCT.md)."

  - type: dropdown
    id: willingness
    attributes:
      label: Willingness to Contribute
      description: "Are you willing to contribute to the resolution of this issue by submitting a pull request?"
      options:
        - "Yes, I would like to work on this issue."
        - "No, I am reporting this issue but do not wish to work on it."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "Please review the information you've entered above and submit your report. We appreciate your contribution!"
