---
blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.gg/BwuMen4XEE
    about: Head over to our Discord community to ask questions and get help.
  - name: Docs
    url: https://platinfra.github.io/
    about: Check out our docs for information about how to use platinfra.
