name: Install Python dependencies
description: Install all core and optional Python dependencies
inputs:
  pythonVersion:
    description: Python version to set up (see actions/setup-python@v4)
    required: true
  dependencyType:
    description: The type of dependencies to install (dev or docs)
    required: true
    default: "dev"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.pythonVersion }}
        cache: "pip"
        cache-dependency-path: |
          requirements-dev.txt
          requirements-docs.txt
          pyproject.toml
    - name: Install uv
      run: |
        pip install uv
      shell: bash
    - name: Install dependencies
      run: |
        uv pip install --upgrade pip
        if [[ "${{ inputs.dependencyType }}" == "dev" ]]; then
          uv pip install -r requirements-dev.txt
        elif [[ "${{ inputs.dependencyType }}" == "docs" ]]; then
          uv pip install -r requirements-docs.txt
        fi
        uv pip install -e . --no-deps
      shell: bash
